// Bekreftede gjester — hentet fra invitasjonsliste (kolonne 3 = "Ja")
// Brukes til romfordeling i Sleeping-seksjonen
// Sist oppdatert: 2026-05-04

export const CONFIRMED_GUESTS: string[] = [
  'Alma',
  'Oline',
  'Kjersti Steinsbø',
  'Øystein',
  'Geir',
  'Ragnhild Muriaas',
  'Tor',
  'Erik',
  'Christine',
  'Lennart',
  'Kjersti Nesheim',
  'Njål',
  'Camilla',
  'Kari Nordstoga',
  'Toli',
  'Ragnhild Nordenbord',
  'Ni',
  'Siren',
  'Jørgen',
  'Bettina',
  'Kjell',
  'Arne',
  'Ingrid Enge',
  'Håvard',
  'Ingrid Miljeteig',
  'Liv Karin',
  'Øyvind',
  'Kari Walle',
  'Beate',
  'Kirsti',
  'Ståle',
  'Agnes',
  'Jon',
  'Annabelle',
  'Christian',
  'Anders',
  'Hilde',
  'Tone',
  'Kåre',
  'Heidi',
  'Gaute',
  'Svein',
  'Stig',
  'Tom-Ivar',
  'Niklas',
]

export const GUEST_COUNT = CONFIRMED_GUESTS.length
